<?xml version="1.0" encoding="UTF-8"?>
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase" 
              xmlns:spring="http://www.springframework.org/schema/beans" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://www.springframework.org/schema/beans 
                                  http://www.springframework.org/schema/beans/spring-beans.xsd 
                                  http://www.citrusframework.org/schema/testcase 
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">
    <testcase name="AssertIT">
        <meta-info>
            <author>Christoph Deppisch</author>
            <creationdate>2008-06-16</creationdate>
            <status>FINAL</status>
            <last-updated-by>Christoph Deppisch</last-updated-by>
            <last-updated-on>2008-06-16T00:00:00</last-updated-on>
        </meta-info>
        
        <description>Asserting excpetions</description>
        
        <variables>
            <variable name="failMessage" value="Something went wrong!"/>
        </variables>
        
        <actions>
            <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException">
              <when>
            	  <fail message="Fail once"/>
              </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException"
                    message="Fail again">
              <when>
            	  <fail message="Fail again"/>
              </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException"
                    message="${failMessage}">
                <when>
                  <fail message="${failMessage}"/>
                </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException"
                    message="@contains('wrong')@">
                <when>
                  <fail message="${failMessage}"/>
                </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.ValidationException">
              <when>
                <assert exception="java.io.IOException">
                    <when>
                      <fail message="Fail another time"/>
                    </when>
                </assert>
              </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.ValidationException">
              <when>
                <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException"
                        message="Fail again">
                    <when>
                      <fail message="Fail with nice error message"/>
                    </when>
                </assert>
              </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.ValidationException">
              <when>
                <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException">
                  <when>
                    <echo>
                      <message>Nothing fails here</message>
                    </echo>
                  </when>
                </assert>
              </when>
            </assert>
            
            <assert exception="org.citrusframework.citrus.exceptions.ValidationException">
              <when>
                <assert exception="org.citrusframework.citrus.exceptions.CitrusRuntimeException"
                        message="Must be failing">
                    <when>
                      <echo>
                        <message>Nothing fails here either</message>
                      </echo>
                    </when>
                </assert>
              </when>
            </assert>
        </actions>
    </testcase>
</spring:beans>
